# ==========================================
# Stage 1: Build Nuxt
# ==========================================
FROM node:22-alpine AS builder

WORKDIR /app

# Copy package trước để tận dụng Docker layer cache
COPY package*.json ./

# Cài dependencies chính xác theo package-lock.json
RUN npm ci

# Copy source code
COPY . .

# Build Nuxt production
RUN npm run build


# ==========================================
# Stage 2: Production Runtime
# ==========================================
FROM node:22-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production

# Nitro listen bên trong container
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=3000

# Chỉ copy output cần thiết
COPY --from=builder /app/.output ./.output

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]